### ISSUE TITLE
3. Tasks for workshop participants

### ISSUE THREAD

**Issue by kayinrage** [Selleo/rent-a-thing#14]
# Rules

- Please remember about pair-programming rules
  - Produce code on one computer only (you can research stuff on the other one)
  - Switch every 60 minutes (we will ring a bell for you)
- Please raise your hand or paste a message on Slack if you need a mentor help (we do not want to stalk you ;)) 

# Before you start

- `git checkout master`
- `git pull`
- `git checkout -b imie1-and-imie2-branch`, i.e. `git checkout -b kasia-and-tomek-branch`
- commit stuff...
-  `git pull --rebase origin master`
- `git push origin kasia-and-tomek-branch --force-with-lease`
 
Click [here for other useful GIT commands](https://medium.com/selleo/a-curated-list-of-git-commands-enough-to-keep-your-git-history-flat-288748998132)

# Tasks

## 1. Add possibility to display a single Booking (show)

- [x] modify `routes.rb`
- [x] add show action to the `bookings_controller`
- [x] add show view - with header and all bookings information (customer full name, starts_on, ends_on)
- [x] add "Show" link for each booking on index page which will link to show page
- [x] add "back to photos listing" link on show page 

## 2. Add possibility to archive a single Booking (delete)

- [x] add a new field `archived_at:datetime` to `Booking` model (migration)
- [x] modify `routes.rb`
- [x] add delete action to the `bookings_controller` which will:
  - [x]  set `archived_at` for `booking` to `Time.current`
  - [x] redirects to index page 
  - [x] displays flash_message "Booking has been archived successfully"
- [x] add "archive" link for each booking on index page which will perform delete action
- [x] add "archive this booking" link on show page

## 3. Display page 404 when booking is not available
- [x] booking is NOT available if:
  - [x]  it was already archived 
  - [x] `ends_on` is set to date before `Time.current`
