### ISSUE TITLE
Task for workshop participants

### ISSUE THREAD

**Issue by stevo** [Selleo/rent-a-thing#15]
# Rules

• Please remember about pair-programming rules
   • Produce code on one computer only (you can research stuff on the other one)
   • Switch every 60 minutes (we will ring a bell for you)
• Please raise your hand or paste a message on Slack if you need a mentor help (we do not want to stalk you ;))

# Tasks

- [ ] Create a new API endpoint which meets following requirements
  - responds to `GET v1/booked_days_by_month` 
  - returns a list of all months up till (and including) current one in current year...
  - ...each with a total number of days that were booked in that given month
  - list is returned as JSON

example response (`HTTP 200 OK`)

```json
[
  { "month": "2021-01", "value": 0 },
  { "month": "2021-02", "value": 10 },
  { "month": "2021-03", "value": 20 },
  { "month": "2021-04", "value": 0 },
  { "month": "2021-05", "value": 0 },
  { "month": "2021-06", "value": 0 },
  { "month": "2021-07", "value": 15 },
  { "month": "2021-08", "value": 0 }
]
```

where `{ "month": "2021-02", "value": 10 },` means, that in February there were bookings created (`created_at`) for a total duration of 10 days (`ends_on - starts_on`). Those bookings can take place outside of February.

- [ ] *Allow and handle passing year for which results should be returned (i.e. `GET v1/booked_days_by_month?year=2019`) 
- [ ] *Return `HTTP 400 Bad Request` when year provided was invalid (i.e. `GET v1/booked_days_by_month?year=czikaczikaboom`) 

# New Version

- [ ] Create a new API endpoint which meets following requirements
  - responds to `GET v1/bookings_by_month` 
  - returns a list of all months  in current year...
  - ...each with a total number of bookings that were made for given month
  - list is returned as JSON

example response (`HTTP 200 OK`)

```json
[
  { "month": "2021-01", "value": 0 },
  { "month": "2021-02", "value": 10 },
  { "month": "2021-03", "value": 20 },
  { "month": "2021-04", "value": 0 },
  { "month": "2021-05", "value": 0 },
  { "month": "2021-06", "value": 0 },
  { "month": "2021-07", "value": 15 },
  { "month": "2021-08", "value": 0 },
  { "month": "2021-09", "value": 0 },
  { "month": "2021-10", "value": 0 },
  { "month": "2021-11", "value": 0 },
  { "month": "2021-12", "value": 0 }
]
```

where `{ "month": "2021-02", "value": 10 },` means, that in February there were 10 bookings created (`created_at`).

- [ ] *Allow and handle passing year for which results should be returned (i.e. `GET v1/bookings_by_month?year=2019`) 
- [ ] *Return `HTTP 400 Bad Request` when year provided was invalid (i.e. `GET v1/bookings_by_month?year=czikaczikaboom`) 

# References

## Non-resourceful routing

- https://guides.rubyonrails.org/routing.html#non-resourceful-routes

## Active Record Querying

- https://guides.rubyonrails.org/active_record_querying.html#range-conditions

## Rendering JSON

- https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-json

## Versioning API

- https://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing
- https://github.com/bploetz/versionist

## Operations on enumerables (arrays, hashes etc.)

- https://ruby-doc.org/core-3.0.2/Enumerable.html#method-i-group_by
- https://ruby-doc.org/core-3.0.2/Hash.html#method-i-transform_values
- https://ruby-doc.org/core-3.0.1/Array.html#method-i-map
- https://ruby-doc.org/core-3.0.1/Array.html#method-i-sum

## Operations on dates

- https://api.rubyonrails.org/classes/Date.html#method-c-current
- https://api.rubyonrails.org/v6.1.4/classes/DateAndTime/Calculations.html#method-i-beginning_of_year
- https://rubyapi.org/3.0/o/datetime#method-i-strftime

## Tools

- https://insomnia.rest
- https://www.postman.com

## Other

- https://jsonapi.org
- https://github.com/graphiti-api/graphiti
- https://jsonapi-resources.com
- https://guides.rubyonrails.org/api_app.html
- https://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html
